### ISSUE TITLE
401 The signature does not match

### ISSUE THREAD

**Issue by ismaelw** [akamai/akamaipowershell#48]
Hi there

Not sure if this issue makes sense here.

Using the PowerShell Module I am able to make Requests (also the one mentioned below).
But because I am in an environment where I should not really use a Module and all the many many functions in there I tried extracting the necessary files (Invoke-AkamaiRestMethod, Crypto, Get-AkamaiCredentials and Sanitize-QueryString)

I am then trying to create a new group in Identity Management with the following body 
`$Body= @{
    groupName = $groupName
} | ConvertTo-Json` 

Analyzing the code everything seems to be working fine. Auth Header is created correctly including the timestamp in UTC format, nonce and signature. I did not change anything in the files mentioned above.

Running `$newGroup = Invoke-AkamaiRestMethod -Method POST -EdgeRCFile $EdgeRCFile -Path "/identity-management/v3/user-admin/groups/$parentGroupID" -Body $Body` then ends in my 401 error.

Am I missing something? Thank you so much for your assistance.

**Comment by stuart-macleod-akamai** [comment]
Hi @ismaelw, there's nothing obviously wrong in your code, and I have tested the exact commands in my lab and they work fine. What is the value of $parentGroupID? Also, do you have the ability to capture the request using something like Fiddler or Charles that you can share? The error you are seeing commonly happens when the body is not included for some reason, or in rare cases when the clock on your OS is out of sync with the Akamai servers. They need to be within 30s or the auth fails

**Comment by ismaelw** [comment]
Hi @stuart-macleod-akamai 

Thank you so much for getting back to me so quickly.

Let me look into Fiddler or Charles and install it so I can provide the captured requests.

The $parentGroupID holds the integer ID of the Group in which I want to create a new group which works in both Postman and using the PowerShell module itself. This is why this all seems to be pretty strange to me.

I will get back with news as soon as possible.

**Comment by ismaelw** [comment]
Hi @stuart-macleod-akamai 

I am now able to capture requests using Fiddler.
Which information could help you?

**Comment by stuartio** [comment]
Can you send a capture of the full request and response please? I think
fiddler can export them as json

**Comment by stuartio** [comment]
Ok sure. Please email it to ***@***.*** and I'll take a look. If we
can't figure it out we can maybe have a live session this week some time.

**Comment by ismaelw** [comment]
Thank you so much for your effort. Unfortunately GitHub censored your email address :)

**Comment by stuartio** [comment]
Dang. It's smacleod at akamai dot com

**Comment by ismaelw** [comment]
Perfect! I sent you the export 😃

**Comment by stuartio** [comment]
OK so I have been able to reproduce the issue, and while I don't have have a solution the issue seems to be related to the non-ascii characters in the new group name. The "ü" and "ö" are confusing the signature generation I think, and the same happens when I use New-IDMGroup directly. But if I change those characters to ascii "u" and "o" I don't get the error. I'll figure out why this is happening and put out a fix as soon as I can, but in the meantime can you test your script with only ascii-characters to see if that unblocks you in the short term?

**Comment by ismaelw** [comment]
Wow. Here in Switzerland we use many umlauts. This is why I always test my scripts using some to make sure I get errors due to these early in the process. But somehow it didn't ever occur to me right now that it might be the issue here.

Thank you very much for figuring this out. I need to check on my end if in our use case a sanitizing of the groupName is a possibility.

But for now I can for sure use ASCII only characters while developing.

Thank you so much for looking into this!

Best regards,
Ismael

**Comment by stuartio** [comment]
Happy to help. I'll figure out a way of handling the input, I imagine it is
entirely possible. It just hasn't come up in our testing before. Once we
get it fixed we'll make sure to add some tests for just this scenario!

**Comment by ismaelw** [comment]
In fact I was just able to use non-ascii characters now just by switching the body hashing part inside "Invoke-AkamaiRestMethod.ps1" from

`$Body_Hash = [System.Convert]::ToBase64String($Body_SHA256.ComputeHash([System.Text.Encoding]::ASCII.GetBytes($Body.Substring(0, $MaxBody))))`

to use UTF8 instead of ASCII:
`$Body_Hash = [System.Convert]::ToBase64String($Body_SHA256.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($Body.Substring(0, $MaxBody))))`

And the same change I did to the file "Crypto.ps1".

Not sure if this is an acceptable approach already but I thought I might share it with you

**Comment by stuartio** [comment]
If it works, it's perfectly acceptable. 🙂 I'll test it internally and put
in a patch shortly. Thanks!
